alias: Schedule AAPS-CI
description: ""
triggers:
  - trigger: time_pattern
    hours: "6"
    minutes: "0"
    seconds: "0"
  - trigger: state
    entity_id:
      - binary_sensor.github_new_commit_available
    enabled: false
    alias: Force build whenever state "New Commit" changes (disabled by defauly)
conditions:
  - condition: numeric_state
    entity_id: sensor.github_latest_commit_age_hours
    below: 72
    above: 0
  - condition: state
    entity_id: binary_sensor.github_new_commit_available
    state: "on"
actions:
  - action: script.trigger_github_aaps_ci
    data: {}
  - action: logbook.log
    data:
      name: AAPS-CI Schedule
      message: >-
        AAPS-CI Build triggered for commit {{
        states('sensor.github_latest_commit_sha')[:7] }}
      entity_id: binary_sensor.github_new_commit_available
  - action: input_text.set_value
    metadata: {}
    target:
      entity_id: input_text.github_last_built_sha
    data:
      value: "{{ states('sensor.github_latest_commit_sha') }}"
    alias: Set github_last_built_sha
mode: single
