# This automation schedules the AAPS-CI build to run every 6 hours,
# but only if there is a new commit in the GitHub repository that is less than 72 hours old.

# The "Force build" trigger is disabled by default, but can be enabled to trigger a build whenever the "New Commit" state changes. 
# Use with care: enabling this trigger will cause a build to run immediately whenever a new commit is detected,
# regardless of the time of day or the age of the commit!


alias: Schedule AAPS-CI
description: ""
triggers:
  - trigger: time_pattern
    hours: "6"
    minutes: "0"
    seconds: "0"
  - trigger: state
    entity_id:
      - binary_sensor.github_new_commit_available
    enabled: false
    alias: Force build whenever state "New Commit" changes (disabled by defauly)
conditions:
  - condition: numeric_state
    entity_id: sensor.github_latest_commit_age_hours
    below: 72
  - condition: state
    entity_id: binary_sensor.github_new_commit_available
    state: "on"
actions:
  - action: script.trigger_github_aaps_ci
    data: {}
  - action: logbook.log
    data:
      name: AAPS-CI Schedule
      message: >-
        AAPS-CI Build triggered for commit {{
        states('sensor.github_latest_commit_sha')[:7] }}
      entity_id: binary_sensor.github_new_commit_available
mode: single
