# configuration.yaml is used for for storing the configuration of Home Assistant.
# Make sure it contains the followig lines to enable loading additional packages ans scrips

homeassistant:
  packages: !include_dir_named packages

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

