
# Note: Make sure secrets are imported from script.yaml
script: !include scripts.yaml

# Add AAPS CI rest sensor to HA configuration
sensor:

  # AAPS CI Worflow
  # Note: In the resource url below change
  # <YOUR_GITHUB_OWNER_NAME>      repo_user to you forked repo username
  # <YOUR_GITHUB_FORKEDREPO_NAME> Your forked repo name (e.g. AndroidAPS)
  # <YOUR_AAPS_CI_WORKFLOWID>     Your workflow ID (hint: use ci_workflows.sh)

  - platform: rest
    name: AndroidAPS Workflow Status
    resource: https://api.github.com/repos/<YOUR_GITHUB_OWNER_NAME>/<YOUR_GITHUB_FORKEDREPO_NAME>/actions/workflows/<YOUR_AAPS_CI_WORKFLOWID>/runs
    headers:
      Authorization: !secret aaps_ci_access_token_header
    value_template: "{{ value_json.workflow_runs[0].status }}"
    json_attributes_path: "$.workflow_runs[0]"
    json_attributes:
      - created_at
      - status
      - conclusion
      - name
      - run_number
      - head_branch

# Add AAPS CI sensor templates to HA configuration

template:
  - sensor:
      # AAPS-CI
      - name: "AndroidAPS Workflow Name"
        state: "{{ state_attr('sensor.androidaps_workflow_status', 'name') }}"
      - name: "AndroidAPS Workflow Branch"
        state: "{{ state_attr('sensor.androidaps_workflow_status', 'head_branch') }}"
      - name: "AndroidAPS Workflow Run Number"
        state: "{{ state_attr('sensor.androidaps_workflow_status', 'run_number') }}"
      - name: "AndroidAPS Workflow Created At"
        state: "{{ state_attr('sensor.androidaps_workflow_status', 'created_at') }}"
      - name: "AndroidAPS Workflow Conclusion"
        state: "{{ state_attr('sensor.androidaps_workflow_status', 'conclusion') }}"
      - name: "CI Status Label"
        state: >
          {% set sc = state_attr('sensor.androidaps_workflow_status', 'conclusion') %}
          {% set s = states('sensor.androidaps_workflow_status') %}
          {% if sc == 'cancelled' %}
            ⛔ Cancelled
          {% elif sc == 'failure' %}
            ❌ Failed
          {% elif s == 'queued' %}
            ⏳ Queued
          {% elif s == 'in_progress' %}
            🟠 Running
          {% elif s == 'completed' %}
            ✅ Completed
          {% else %}
            ⚪ Idle
          {% endif %}

shell_command:
  start_github_aaps_ci: 'bash /config/AAPS-CI/build.sh'

script:
  trigger_github_aaps_ci:
    alias: "Start GitHub AAPS CI"
    sequence:
      - service: shell_command.start_github_aaps_ci
